name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version Tag (v1.0.0)"
        type: string
        required: true
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Fetch depth 0 is required for Changelog generation
      - name: Checkout      
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.1
          stable: false

      - name: Go Test
        run: |
          make test
          
      - name: Cross Build
        run: |
          make package
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.inputs.tag }}
          message: "create tag"
          token: ${{ secrets.GITHUB_TOKEN }}
